### ISSUE TITLE
导出

### ISSUE THREAD

**Issue by hb0730** [huanshare/huan-swagger#3]
请问近期是否有考虑过huan-swagger 支持导出【pdf,html】的功能呢？

**Comment by huanshare** [comment]
可以的，后续加上

**Comment by hb0730** [comment]
现在我想使用您的huan-swagger 发现maven无法下载依赖，我的同事也是如此

**Comment by huanshare** [comment]
maven地址改成阿里的试试

**Comment by hb0730** [comment]
您好、我的maven设置就是阿里云maven的仓库、但是还是无法下载您给的maven坐标

**Comment by huanshare** [comment]
<dependency>
<groupId>com.github.huanshare</groupId>
   <artifactId>swagger-ui-layer</artifactId>
   <version>1.0.0</version>
 </dependency> 
 这个不能用？

**Comment by hb0730** [comment]
是的，按照你给的坐标，maven无法下载依赖，

**Comment by hb0730** [comment]
已经好了，可能是公司的网的问题，非常感谢，耐心的回复
