### ISSUE TITLE
maven依赖错误

### ISSUE THREAD

**Issue by hb0730** [huanshare/huan-swagger#4]
关于您的swagger-ui-layer 1.0.0版本，我发现我无法下载您的依赖，但是从github clone 下来的project 是可以运行的，我全新新建project 并依赖您的swagge-ui-layer是失败的，您可以试着尝试一下，因为我发现我依赖您给出的   `小伙伴的地址（https://github.com/ohcomeyes/swagger-ui-layer ）`依赖下来的也是成功的，

**Comment by huanshare** [comment]
如果你本地运行过demo，demo会自动在本地打包成功，所以能运行，如果你新建一个demo项目，就看你本地网络和本地maven的下载能力了，这个问题也困扰我很久了

**Comment by hb0730** [comment]
期待解决这个问题，

**Comment by baiyun1102** [comment]
maven依赖报错呢
